AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaName:
    Description: " Enter a name that describes the purpose of your function., up to 64 characters in length"
    Type: String

  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

  LambdaMemorySize:
    Type: String
    Default: "128"
    Description: The value can be any multiple of 1 MB.Max= 10240,Min= 128. The default value is 128 MB.

  EcrImageUri:
    Description: ECR image URI
    Type: String

Resources:
  awslambdafunc:
    Type: AWS::Lambda::Function
    Properties:
      Description: "LambdaFunciton"
      Environment:
        Variables:
          ENV:
            Fn::Sub: ${EnvName}
          TZ: UTC
      FunctionName: !Join ["-", [!Ref LambdaName, app]]
      PackageType: Image
      Role: arn:aws:iam::accountid:role/lambdarolename
      #Timeout cannot be parameterize
      Timeout: 300
      Code:
        ImageUri: !Ref "EcrImageUri"
      Architectures:
        - x86_64
      MemorySize: !Ref LambdaMemorySize
      Tags:
        [
          { "Key": "Stage", "Value": "QA" },
          { "Key": "Owner", "Value": "lambda" },
        ]
