# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    # Triggers the workflow on push or pull request events but only for the main branch
    branches: [buildandpush]
    paths:
      - ".github/workflows/main.yml"
      - "app/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mlproject
          APP_TAG: "myapp5.0"
        run: |
          echo "build started...."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_TAG-GITHUB_RUN_NUMBER app/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$APP_TAG-$GITHUB_RUN_NUMBER
          echo "image has been pushed"
          echo $APP_TAG-$GITHUB_RUN_NUMBER
          docker rmi $ECR_REGISTRY/$ECR_REPOSITORY:$APP_TAG-$GITHUB_RUN_NUMBER
